language: python
python:
  - "2.7"
# install dependencies
install: "pip install -r requirements.txt"
# build after each commit
script: script/build
# auto deploy on when merge on master
deploy:
  provider: script
  script: script/deploy_prod
  on:
    branch: master
